name: Share data between jobs

on:
  push:
    branches: "main"

jobs:
  job_1:
    name: create an new artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          bash .github/scripts/dummy_script.sh
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: assets/metadata/timestamp.txt

  job_2:
    name: download, update, and reupload the artifact
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat timestamp.txt`
          echo $value
          echo $value > new_content.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: new_content.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat assets/metadata/timestamp.txt`
          echo The result is $value
          new_content=`cat new_content.txt`
          echo Here is the new content $new_content
          git config --local user.name actions-user

          git config --local user.email "actions@github.com"  
          
          git fetch
          
          git branch

          git branch -r 

          git checkout alpha

          git add new_content.txt

          git commit -m "update new content"

          git push origin alpha 
          
          git status



          

          # git add assets/metadata/module_data.py

          # git add assets/metadata/module_data.csv

          # git commit -am "update metadata records" 
 
          # git push origin metadata_workflow
