name: Run on a schedule

on:
  schedule:
    - cron: '34/2 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"

      - name: print a message
        run: |
          echo "the time is now $( date )"