name: Run on a schedule

on:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '20 * * * *'

jobs:
  did_it_run:
    name: Did it run?
    runs-on: ubuntu-latest
    steps:
      - name: print a message
        run: |
          echo "the time is now $( date )"