# This is a workflow to pull all of the metadata from all of the modules into a single file
# each time something is merged to main, this workflow will run and rebuild the metadata file.

name: pull_metadata

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.check_if_changed.outputs.any_change }}
    steps:
      - uses: actions/checkout@v3

      - id: step1
        run: |
          echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      
      - id: Process_Metadata
        run: |
          bash .github/scripts/dummy_script.sh
      
      - id: check_if_changed  
        run: |
          changes=$(git diff assets/metadata/timestamp.txt | wc -l)
          echo  there is $changes new line
          any_changes=$([ $changes -gt 0 ] && echo "true" || echo "false")
          echo the any_changes variable is now $any_changes
          echo "any_change=$any_changes" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
          OUTPUT3: ${{needs.job1.outputs.output3}}
        run: echo "$OUTPUT1 $OUTPUT2 $OUTPUT3"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs.output3 == 'true'  
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
          OUTPUT3: ${{needs.job1.outputs.output3}}
        run: echo "$OUTPUT1 $OUTPUT2 $OUTPUT3"

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
     - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
  
  
  # # If the processed metadata has changed at all, then we update the files:
  # update_data_files:
  #   runs-on: ubuntu-latest
  #   needs: [ process_metadata ]
  #   if: needs.process_metadata.outputs.any_changes == true
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:  
  #     - uses: actions/checkout@v3

  #     - name: Set up Python 3.x
  #       uses: actions/setup-python@v4
  #       with:
  #         # Semantic version range syntax or exact version of a Python version
  #         python-version: '3.x'

  #     - name: Install Python dependencies
  #       run: python -m pip install --upgrade pip pandas

  #     - name: Create csv from python file
  #       run: |
  #         python assets/metadata/module_data.py

  #     - name: Commit newly updated files
  #       run:
  #         git config --local user.name actions-user

  #         git config --local user.email "actions@github.com" 
 
  #         git checkout metadata_workflow

  #         git fetch

  #         git add assets/metadata/module_data.py

  #         git add assets/metadata/module_data.csv

  #         git commit -am "update metadata records" 
 
  #         git push origin metadata_workflow



          