# This is a workflow to pull all of the metadata from all of the modules into a single file
# each time something is merged to main, this workflow will run and rebuild the metadata file.

name: commit_to_branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: "main"
    paths-ignore:
      - 'assets/**'
      - '_for_authors/**'
      - '_module_templates/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # # If changes were made to the python file, then we want to push those changes
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: does anything work?
        run: |
          echo "does anything work?"
          bash .github/scripts/dummy_script.sh
          echo "script ran"

      # - name: Create csv from python file
      #   run: |
      #     bash .github/scripts/dummy_script.sh
          
      - name: Commit newly updated files
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com" 
 
          git stash

          git checkout alpha

          git fetch

          git add assets/metadata/timestamp.txt
          #git add assets/metadata/module_data.py

          #git add assets/metadata/module_data.csv

          git commit -am "update metadata records" 
 
          git push origin alpha



          